### ISSUE TITLE
Refactoring the technical-documentation away from ExpressVPN

### ISSUE THREAD

**Issue by proffapt** [sheharyaar/iit-kgp-network#13]
Since ExpressVPN is not the best now; it has a new contender -- Speedify, the whole testing thing shall be changed to Speedify if we get some tester(I might be the one; but I ain't into gaming so that will not suffice). Speedify has active servers in Mumbai, India and no future plans to remove them and cheaper( in terms of 3-yr plan ) than ExpressVPN. 

Thus a general suggestion to change the essence of documentation to something not based on ExpressVPN or atleast mention about the "now" issue with ExpressVPN in the documentation as a highlight.
Shall I make a PR regarding this after Speedify test results PR gets merged?

**Comment by sheharyaar** [comment]
I kept expressvpn as the bar for the benchmark because not only being so effective, it's working is very much simple and it has it's core open-sourced. It basically uses wolfSSL (lightweight) and creates a tunnel with the encrypted traffic. So anyone interested can build a wrapper around it and host their own vpn. This was what I wanted to achieve initially, but due to time crunch I couldn't. It has nothing to do with it's performance.

**Comment by proffapt** [comment]
aha, gotcha so it looks fine then; for now

**Comment by sheharyaar** [comment]
Yeah you can craete a PR regarding the current issue with expressvpn and we can highlight speedify for now in the benchmarks.

**Comment by proffapt** [comment]
> Yeah you can craete a PR regarding the current issue with expressvpn and we can highlight speedify for now in the benchmarks.

On my way (was trying to sleep for past 2 hrs; unsuccessful maybe after this can rest in peace (个_个) )
