### ISSUE TITLE
Move contributions to main README

### ISSUE THREAD

**Issue by sheharyaar** [sheharyaar/iit-kgp-network#17]

**Comment by proffapt** [comment]
Moved the Contribution guidelines and Contributors list to main readme in the commit: [Moving Contribution guidelines and Contributors list to README.md](https://github.com/sheharyaar/iit-kgp-network/commit/614d1a9bb2808ce6cdbaaef1f19c0db0918b292b)

Will wait for your approval to close this issue, suggest anything you have regarding this so that everything is in-phase

**Comment by sheharyaar** [comment]
Good work! But for the future PRs I would suggest for all contributers including me to create a branch and a PR for changes

**Comment by proffapt** [comment]
> Good work! But for the future PRs I would suggest for all contributers including me to create a branch and a PR for changes

Yes, exactly. Since this is something maintained by one person, PRs will help to decrease chaos; I would like to just directly push a change regarding [d4d7686](https://github.com/sheharyaar/iit-kgp-network/pull/22/commits/d4d7686f18a9cf147109ca683bda0e4de03ddc13), that `feature/AmazingFeature` was meant as an alternative like either type this or that; but I see its not helping rather will create problems so I will just fix it a bit and directly push and will continue with proper PR method after this
